paths:
  /api/shippment/update-status/{id}:
    patch:
      summary: "Update the status of a shipment"
      description: "This endpoint allows updating the status of an existing shipment."
      tags:
        - "shippment"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: "ID of the shipment to update"
          required: true
          type: "string"
        - in: "body"
          name: "status"
          description: "New status for the shipment"
          required: true
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                description: "Updated state of the shipment"
            required:
              - "status"
